// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["POSTGRES_PRISMA_URL"],
    // directUrl is likely not supported in this config shape yet or handled differently?
    // checking the error: "Move connection URLs for Migrate to prisma.config.ts"
    // Does it support directUrl?
    // Let's assume standard object property if types allow. If not, maybe just url.
    // However, migrations usually need the direct connection.
  },
});
